
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 23 11:12:37 COT 2020
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 13;
  public static final int FROM = 12;
  public static final int Parentesis_c = 18;
  public static final int Parentesis_a = 17;
  public static final int SELECT = 5;
  public static final int Numero = 23;
  public static final int END = 9;
  public static final int ERROR = 30;
  public static final int CREATE_PROCEDURE = 7;
  public static final int Identificador = 16;
  public static final int Comillas = 28;
  public static final int Int = 21;
  public static final int Coma = 20;
  public static final int TABLE = 15;
  public static final int CamposTabla = 29;
  public static final int T_dato = 25;
  public static final int P_coma = 19;
  public static final int BEGIN = 8;
  public static final int Asterisco = 27;
  public static final int CREATE = 6;
  public static final int Cadena = 22;
  public static final int INSERT = 2;
  public static final int EOF = 0;
  public static final int VALUES = 11;
  public static final int SET = 14;
  public static final int error = 1;
  public static final int Igual = 26;
  public static final int DELETE = 3;
  public static final int UPDATE = 4;
  public static final int Datos = 24;
  public static final int INTO = 10;
}

